KR_INT 1 int
IDN 1 main
L_ZAGRADA 1 (
KR_VOID 1 void
D_ZAGRADA 1 )
L_VIT_ZAGRADA 1 {
KR_RETURN 2 return
IDN 2 printf
L_ZAGRADA 2 (
NIZ_ZNAKOVA 2 "hello world!\n"
D_ZAGRADA 2 )
TOCKAZAREZ 2 ;
D_VIT_ZAGRADA 3 }
