#include "Pravila.h"

vector< string > dohvatiStanja() {
	vector< string > ret;
	ret.push_back("S_pocetno");
	ret.push_back("S_komentar");
	ret.push_back("S_jednolinijskiKomentar");
	ret.push_back("S_string");
	return ret;
}
vector< string > dohvatiImena() {
	vector< string > ret;
	ret.push_back("IDN");
	ret.push_back("BROJ");
	ret.push_back("ZNAK");
	ret.push_back("NIZ_ZNAKOVA");
	ret.push_back("KR_BREAK");
	ret.push_back("KR_CHAR");
	ret.push_back("KR_CONST");
	ret.push_back("KR_CONTINUE");
	ret.push_back("KR_ELSE");
	ret.push_back("KR_FOR");
	ret.push_back("KR_IF");
	ret.push_back("KR_INT");
	ret.push_back("KR_RETURN");
	ret.push_back("KR_VOID");
	ret.push_back("KR_WHILE");
	ret.push_back("PLUS");
	ret.push_back("OP_INC");
	ret.push_back("MINUS");
	ret.push_back("OP_DEC");
	ret.push_back("OP_PUTA");
	ret.push_back("OP_DIJELI");
	ret.push_back("OP_MOD");
	ret.push_back("OP_PRIDRUZI");
	ret.push_back("OP_LT");
	ret.push_back("OP_LTE");
	ret.push_back("OP_GT");
	ret.push_back("OP_GTE");
	ret.push_back("OP_EQ");
	ret.push_back("OP_NEQ");
	ret.push_back("OP_NEG");
	ret.push_back("OP_TILDA");
	ret.push_back("OP_I");
	ret.push_back("OP_ILI");
	ret.push_back("OP_BIN_I");
	ret.push_back("OP_BIN_ILI");
	ret.push_back("OP_BIN_XILI");
	ret.push_back("ZAREZ");
	ret.push_back("TOCKAZAREZ");
	ret.push_back("L_ZAGRADA");
	ret.push_back("D_ZAGRADA");
	ret.push_back("L_UGL_ZAGRADA");
	ret.push_back("D_UGL_ZAGRADA");
	ret.push_back("L_VIT_ZAGRADA");
	ret.push_back("D_VIT_ZAGRADA");
	return ret;
}
vector< pair< string, string > > dohvatiPravila() {
	vector< pair< string, string > > ret;
	ret.push_back(make_pair("S_pocetno", "\\t|\\_"));
	ret.push_back(make_pair("S_pocetno", "\\n"));
	ret.push_back(make_pair("S_pocetno", "//"));
	ret.push_back(make_pair("S_jednolinijskiKomentar", "\\n"));
	ret.push_back(make_pair("S_jednolinijskiKomentar", "(\\(|\\)|\\{|\\}|\\||\\*|\\\\|\\$|\\t|\\n|\\_|!|\"|#|%|&|'|+|,|-|.|/|0|1|2|3|4|5|6|7|8|9|:|;|<|=|>|?|@|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|[|]|^|_|`|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|~)"));
	ret.push_back(make_pair("S_pocetno", "/\\*"));
	ret.push_back(make_pair("S_komentar", "\\*/"));
	ret.push_back(make_pair("S_komentar", "\\n"));
	ret.push_back(make_pair("S_komentar", "(\\(|\\)|\\{|\\}|\\||\\*|\\\\|\\$|\\t|\\n|\\_|!|\"|#|%|&|'|+|,|-|.|/|0|1|2|3|4|5|6|7|8|9|:|;|<|=|>|?|@|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|[|]|^|_|`|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|~)"));
	ret.push_back(make_pair("S_pocetno", "\""));
	ret.push_back(make_pair("S_string", "\"((\\(|\\)|\\{|\\}|\\||\\*|\\\\|\\$|\\t|\\_|!|#|%|&|'|+|,|-|.|/|0|1|2|3|4|5|6|7|8|9|:|;|<|=|>|?|@|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|[|]|^|_|`|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|~)|\\\\\")*\""));
	ret.push_back(make_pair("S_pocetno", "break"));
	ret.push_back(make_pair("S_pocetno", "char"));
	ret.push_back(make_pair("S_pocetno", "const"));
	ret.push_back(make_pair("S_pocetno", "continue"));
	ret.push_back(make_pair("S_pocetno", "else"));
	ret.push_back(make_pair("S_pocetno", "for"));
	ret.push_back(make_pair("S_pocetno", "if"));
	ret.push_back(make_pair("S_pocetno", "int"));
	ret.push_back(make_pair("S_pocetno", "return"));
	ret.push_back(make_pair("S_pocetno", "void"));
	ret.push_back(make_pair("S_pocetno", "while"));
	ret.push_back(make_pair("S_pocetno", "(_|(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z))(_|(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z)|(0|1|2|3|4|5|6|7|8|9))*"));
	ret.push_back(make_pair("S_pocetno", "(0|1|2|3|4|5|6|7|8|9)(0|1|2|3|4|5|6|7|8|9)*"));
	ret.push_back(make_pair("S_pocetno", "0(X|x)((0|1|2|3|4|5|6|7|8|9)|a|b|c|d|e|f|A|B|C|D|E|F)((0|1|2|3|4|5|6|7|8|9)|a|b|c|d|e|f|A|B|C|D|E|F)*"));
	ret.push_back(make_pair("S_pocetno", "'(\\(|\\)|\\{|\\}|\\||\\*|\\\\|\\$|\\_|!|\"|#|%|&|+|,|-|.|/|0|1|2|3|4|5|6|7|8|9|:|;|<|=|>|?|@|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|[|]|^|_|`|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|~)'"));
	ret.push_back(make_pair("S_pocetno", "'\\\\(\\(|\\)|\\{|\\}|\\||\\*|\\\\|\\$|\\_|!|\"|#|%|&|'|+|,|-|.|/|0|1|2|3|4|5|6|7|8|9|:|;|<|=|>|?|@|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|[|]|^|_|`|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|~)'"));
	ret.push_back(make_pair("S_pocetno", "++"));
	ret.push_back(make_pair("S_pocetno", "--"));
	ret.push_back(make_pair("S_pocetno", "+"));
	ret.push_back(make_pair("S_pocetno", "-"));
	ret.push_back(make_pair("S_pocetno", "\\*"));
	ret.push_back(make_pair("S_pocetno", "/"));
	ret.push_back(make_pair("S_pocetno", "%"));
	ret.push_back(make_pair("S_pocetno", "="));
	ret.push_back(make_pair("S_pocetno", "<"));
	ret.push_back(make_pair("S_pocetno", "<="));
	ret.push_back(make_pair("S_pocetno", ">"));
	ret.push_back(make_pair("S_pocetno", ">="));
	ret.push_back(make_pair("S_pocetno", "=="));
	ret.push_back(make_pair("S_pocetno", "!="));
	ret.push_back(make_pair("S_pocetno", "!"));
	ret.push_back(make_pair("S_pocetno", "~"));
	ret.push_back(make_pair("S_pocetno", "&&"));
	ret.push_back(make_pair("S_pocetno", "\\|\\|"));
	ret.push_back(make_pair("S_pocetno", "&"));
	ret.push_back(make_pair("S_pocetno", "\\|"));
	ret.push_back(make_pair("S_pocetno", "^"));
	ret.push_back(make_pair("S_pocetno", ","));
	ret.push_back(make_pair("S_pocetno", ";"));
	ret.push_back(make_pair("S_pocetno", "\\("));
	ret.push_back(make_pair("S_pocetno", "\\)"));
	ret.push_back(make_pair("S_pocetno", "\\{"));
	ret.push_back(make_pair("S_pocetno", "\\}"));
	ret.push_back(make_pair("S_pocetno", "["));
	ret.push_back(make_pair("S_pocetno", "]"));
	return ret;
}
map< int, vector< pair< string, string > > > dohvatiAkcije() {
	map< int, vector< pair< string, string > > >ret;
	ret[0].push_back(make_pair("-", ""));
	ret[1].push_back(make_pair("-", ""));
	ret[1].push_back(make_pair("NOVI_REDAK", ""));
	ret[2].push_back(make_pair("-", ""));
	ret[2].push_back(make_pair("UDJI_U_STANJE", "S_jednolinijskiKomentar"));
	ret[3].push_back(make_pair("-", ""));
	ret[3].push_back(make_pair("NOVI_REDAK", ""));
	ret[3].push_back(make_pair("UDJI_U_STANJE", "S_pocetno"));
	ret[4].push_back(make_pair("-", ""));
	ret[5].push_back(make_pair("-", ""));
	ret[5].push_back(make_pair("UDJI_U_STANJE", "S_komentar"));
	ret[6].push_back(make_pair("-", ""));
	ret[6].push_back(make_pair("UDJI_U_STANJE", "S_pocetno"));
	ret[7].push_back(make_pair("-", ""));
	ret[7].push_back(make_pair("NOVI_REDAK", ""));
	ret[8].push_back(make_pair("-", ""));
	ret[9].push_back(make_pair("-", ""));
	ret[9].push_back(make_pair("UDJI_U_STANJE", "S_string"));
	ret[9].push_back(make_pair("VRATI_SE", "0"));
	ret[10].push_back(make_pair("NIZ_ZNAKOVA", ""));
	ret[10].push_back(make_pair("UDJI_U_STANJE", "S_pocetno"));
	ret[11].push_back(make_pair("KR_BREAK", ""));
	ret[12].push_back(make_pair("KR_CHAR", ""));
	ret[13].push_back(make_pair("KR_CONST", ""));
	ret[14].push_back(make_pair("KR_CONTINUE", ""));
	ret[15].push_back(make_pair("KR_ELSE", ""));
	ret[16].push_back(make_pair("KR_FOR", ""));
	ret[17].push_back(make_pair("KR_IF", ""));
	ret[18].push_back(make_pair("KR_INT", ""));
	ret[19].push_back(make_pair("KR_RETURN", ""));
	ret[20].push_back(make_pair("KR_VOID", ""));
	ret[21].push_back(make_pair("KR_WHILE", ""));
	ret[22].push_back(make_pair("IDN", ""));
	ret[23].push_back(make_pair("BROJ", ""));
	ret[24].push_back(make_pair("BROJ", ""));
	ret[25].push_back(make_pair("ZNAK", ""));
	ret[26].push_back(make_pair("ZNAK", ""));
	ret[27].push_back(make_pair("OP_INC", ""));
	ret[28].push_back(make_pair("OP_DEC", ""));
	ret[29].push_back(make_pair("PLUS", ""));
	ret[30].push_back(make_pair("MINUS", ""));
	ret[31].push_back(make_pair("OP_PUTA", ""));
	ret[32].push_back(make_pair("OP_DIJELI", ""));
	ret[33].push_back(make_pair("OP_MOD", ""));
	ret[34].push_back(make_pair("OP_PRIDRUZI", ""));
	ret[35].push_back(make_pair("OP_LT", ""));
	ret[36].push_back(make_pair("OP_LTE", ""));
	ret[37].push_back(make_pair("OP_GT", ""));
	ret[38].push_back(make_pair("OP_GTE", ""));
	ret[39].push_back(make_pair("OP_EQ", ""));
	ret[40].push_back(make_pair("OP_NEQ", ""));
	ret[41].push_back(make_pair("OP_NEG", ""));
	ret[42].push_back(make_pair("OP_TILDA", ""));
	ret[43].push_back(make_pair("OP_I", ""));
	ret[44].push_back(make_pair("OP_ILI", ""));
	ret[45].push_back(make_pair("OP_BIN_I", ""));
	ret[46].push_back(make_pair("OP_BIN_ILI", ""));
	ret[47].push_back(make_pair("OP_BIN_XILI", ""));
	ret[48].push_back(make_pair("ZAREZ", ""));
	ret[49].push_back(make_pair("TOCKAZAREZ", ""));
	ret[50].push_back(make_pair("L_ZAGRADA", ""));
	ret[51].push_back(make_pair("D_ZAGRADA", ""));
	ret[52].push_back(make_pair("L_VIT_ZAGRADA", ""));
	ret[53].push_back(make_pair("D_VIT_ZAGRADA", ""));
	ret[54].push_back(make_pair("L_UGL_ZAGRADA", ""));
	ret[55].push_back(make_pair("D_UGL_ZAGRADA", ""));
	return ret;
}
