#!/bin/bash

TEST_DIR="testovi/"
RUN="./"
BACK="../"
ANALIZATOR="analizator"
GENERATOR="generator"

OUT_EXT="/test.out"
IN_GEN_EXT="/test.san"
IN_ANA_EXT="/test.in"
TEMP_FILE="my_result.txt"
TEMP_TIME="my_time.txt"

lista_krivih=""
vrijeme=0
tocno=0
ukupno=0

testovi=$(ls $TEST_DIR)

if [ $# -ne 0 ] 
then
  testovi=$@
fi

# create executables for generator
echo "Creating executables for generator: " >& 2
make clean >& 2
make >& 2
# change directory to analizator
cd analizator/

# create executables for analyzer
echo "Creating executables for analyzer: " >& 2
make clean >& 2
make >& 2

cd ..
# go back

printf "%-25s %4s %-8s %-8s %s \n" "Test Case" "STAT" "G_TIME" "A_TIME" "TOTAL"
for name in $testovi
do
  # run generator on IN_GEN_FILE
  
  (time $RUN$GENERATOR < $TEST_DIR$name$IN_GEN_EXT 2> /dev/null) &> $TEMP_TIME 
  seconds1=$(cat $TEMP_TIME |grep real |cut -f2 -d'm' |cut -f1 -d's')
  minutes1=$(cat $TEMP_TIME |grep real |cut -f1 -d'm' |cut -f2)
  vrijeme=$(echo "$vrijeme + $seconds1 + 60 * $minutes1" | bc)

  # get output from te time command while redirecting stdout to TEMP_FILE and
  # stderr to stderr

  cd analizator/

  (time $RUN$ANALIZATOR < $BACK$TEST_DIR$name$IN_ANA_EXT > $BACK$TEMP_FILE 2> /dev/null ) &> $BACK$TEMP_TIME 
  seconds2=$(cat $BACK$TEMP_TIME |grep real |cut -f2 -d'm' |cut -f1 -d's')
  minutes2=$(cat $BACK$TEMP_TIME |grep real |cut -f1 -d'm' |cut -f2)
  vrijeme=$(echo "$vrijeme + $seconds2 + 60 * $minutes1" | bc)

  diff $BACK$TEMP_FILE $BACK$TEST_DIR$name$OUT_EXT &> /dev/null

  if [ $? -eq 0 ]
  then
    tocno=$((tocno + 1))
    stat="OK"
  else
    lista_krivih=$lista_krivih" "$name
    stat="WA"
  fi

  gen_time=$(echo "$minutes1 * 60 + $seconds1" | bc)
  ana_time=$(echo "$minutes2 * 60 + $seconds2" | bc)

  test_case_time=$(echo "$gen_time + $ana_time" | bc)

  printf "%-25s %4s %-8.2lf %-8.2lf %-8.2lf \n" $name $stat $gen_time $ana_time $test_case_time

  # going back
  cd ..

  ukupno=$((ukupno + 1))
done

echo "STATS: $tocno/$ukupno IN $vrijeme s"
if [ $tocno -ne $ukupno ]
then
  echo "FAILED: $lista_krivih"
fi

rm $TEMP_FILE $TEMP_TIME
make clean
cd analizator/
make clean
cd ..
